enum TemplateType {
  GET_IS_LOADING = '/TEMPLATE/GET_IS_LOADING',
  SET_IS_LOADING = '/TEMPLATE/SET_IS_LOADING',
  GET_COLLAPSED_DATA = '/TEMPLATE/GET_COLLAPSED_DATA',
  SET_COLLAPSED_DATA = '/TEMPLATE/SET_COLLAPSED_DATA'
}

export default TemplateType;
